[tool.poetry]
name = "pythonproject39"
version = "0.1.0"
description = ""
authors = ["ilonahg <gogilchyn2005ilona@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
